# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "miniconda-latest"
  jobs:
    pre_build:
      - mkdir -p ${READTHEDOCS_OUTPUT}/html/doxygen
      - cd doc/rtd && doxygen
      - cd doc/rtd && python3 parse_xml.py

sphinx:
  configuration: doc/rtd/conf.py

conda:
  environment: doc/rtd/environment.yml

python:
  install:
    - requirements: doc/rtd/requirements.txt
